### ISSUE TITLE
Static compilation and disabling logging

### ISSUE THREAD

**Issue by mike-5345** [augcampos/asterisk-cpp#10]
Hello, 

I am very interested in using your library. Is there any way to add static compilation and a way to totally disable logging?

Thanks,
Mike

**Comment by augcampos** [comment]
Hi there,

What do you mean "static compilation", because will be static linked on use?
 - check wiki examples, on section [build example] ([Examples](https://github.com/augcampos/asterisk-cpp/wiki/Examples))
 g++ Test.cpp -o tt **-lasteriskcpp**

for the disable logging: Yes, please see the example ([link](https://github.com/augcampos/asterisk-cpp/blob/cf3c02d00c2885badf117edeadd3b6f0b1fc05fe/asterisk-cpp/examples/Test.cpp))
- you can set the level to LL_FATAL 
  - LogHandler::getInstance()->setLevel(LL_TRACE); ([Link](https://github.com/augcampos/asterisk-cpp/blob/cf3c02d00c2885badf117edeadd3b6f0b1fc05fe/asterisk-cpp/examples/Test.cpp#L26))
 - or define  DISABLE_LOG_HANDLER & DISABLE_LOG_TOTAL  [(link)](https://github.com/augcampos/asterisk-cpp/blob/cf3c02d00c2885badf117edeadd3b6f0b1fc05fe/asterisk-cpp/asteriskcpp/utils/LogHandler.h#L22)

**Comment by mike-5345** [comment]
Yes I would like to compile to an archive for static linking.

When I define DISABLE_LOG_TOTAL I get this error:
`src/exceptions/ExceptionHandler.cpp: In static member function 'static void asteriskcpp::ExceptionHandler::signalHandler(int)':
src/exceptions/ExceptionHandler.cpp:125:45: error: invalid operands of types 'const char [11]' and 'int' to binary 'operator<<'
                 LOG_ERROR_DATA("Expected: " << SIGSEGV << ", got: " << signal << ", returning");
                                             ^
src/exceptions/ExceptionHandler.cpp:125:17: error: 'LOG_ERROR_DATA' was not declared in this scope
                 LOG_ERROR_DATA("Expected: " << SIGSEGV << ", got: " << signal << ", returning");
                 ^~~~~~~~~~~~~~
src/exceptions/ExceptionHandler.cpp:125:17: note: suggested alternative: 'LOG_ERROR_STR'
                 LOG_ERROR_DATA("Expected: " << SIGSEGV << ", got: " << signal << ", returning");
                 ^~~~~~~~~~~~~~
                 LOG_ERROR_STR
make: *** [Makefile:1500: libasteriskcpp_la-ExceptionHandler.lo] Error 1`

Also, what is the proper way to attempt reconnection if it fails? Currently I am getting a segfault when I create and attempt to connect in a loop.

**Comment by augcampos** [comment]
Hi there,

I had no problem on compile and execute this test (after install via make):

```
#include <iostream>
#include <asteriskcpp/Manager.hpp>

#define DISABLE_LOG_HANDLER
#define DISABLE_LOG_TOTAL

using namespace asteriskcpp;

void eventCallback(const ManagerEvent& me) {
    std::cout << "TEST EVENT START: " << me.getEventName() << std::endl;
    if (me.getEventName() == "NewChannel") {
        std::cout << "E - " << me.toString() << std::endl;
    }
    std::cout << "TEST EVENT: " << me.toLog() << std::endl;
}

int main() {
    std::cout << asteriskcpp::getCurrentTimeStamp() << " START ASTERISK-CPP-TEST" << std::endl;
    LogHandler::getInstance()->setLevel(LL_FATAL);

    ManagerConnection mc;

    try {
        mc.addEventCallback(&eventCallback);

        if (mc.connect("192.168.1.10")) {

            if (mc.login("administrator", "secret")) {

                for (int i = 0; i < 1; i++) {
                    asteriskcpp::EventsAction ea("OFF");
                    mc.sendAction(&ea);
                    ea.setEventMask("ON");
                    mc.sendAction(&ea);
                    asteriskcpp::ManagerResponse* rpc;

                    asteriskcpp::AbsoluteTimeoutAction ata("SIP/1000", 30);
                    rpc = mc.syncSendAction(ata);
                    delete (rpc);

                    asteriskcpp::ListCommandsAction lca;
                    rpc = mc.syncSendAction(lca);
                    delete (rpc);

                    asteriskcpp::CommandAction coma("sip show peers");
                    asteriskcpp::CommandResponse* cr = (asteriskcpp::CommandResponse*) (mc.syncSendAction(coma));
                    std::cout << std::endl << "ZZZZZZ" << cr->toLog() << std::endl;
                    for (std::vector<std::string>::const_iterator it = cr->getResult().begin(); it != cr->getResult().end(); it++) {
                        std::cout << "[" << (*it) << "]" << std::endl;
                    }
                    delete (cr);
                }
                mc.logoff();
            }
            mc.disconnect();
        }
    } catch (Exception e) {
        std::cout << " ERROR :" << e.getMessage() << std::endl;
    }
    std::cout << asteriskcpp::getCurrentTimeStamp() << " END ASTERISK-CPP-TEST" << std::endl;
    exit(0);
}
```

**Comment by augcampos** [comment]
> is there any case where it will log to stdout? Or does this prevent it from sologging totally?

Is not supposed to do it, but could have missed some stdout(printf/cout), if I did open a issue so can be fixed :)

> Also, what is the correct way to attempt a reconnect if one has failed?

Not at the lib level. 
But the connect will return false and you can try again. Please see ([code](https://github.com/augcampos/asterisk-cpp/blob/921423e0d1b6042d0ce2be6d7b9d98af4feb7460/asterisk-cpp/src/manager/ManagerConnection.cpp#L48))

> And is there any way to compile to archive for static linking?

At this time, No.
I try it, some time ago but I was getting to much trouble with the dependency libs.
