### ISSUE TITLE
Example in wiki doesn't work

### ISSUE THREAD

**Issue by linuxdeveloper** [augcampos/asterisk-cpp#4]
Hi,

I tried to test the example in the wiki but I can't compile it correctly, this is error displayed after compilation:

root@debian:~# g++ TestCpp.cpp -o tt -lasteriskcpp
TestCpp.cpp: In function ‘int main()’:
TestCpp.cpp:13:39: error: invalid conversion from ‘void (*)(asteriskcpp::ManagerEvent*)’ to ‘asteriskcpp::onManagerEventCallback_t {aka void (*)(const asteriskcpp::ManagerEvent&)}’ [-fpermissive]
In file included from TestCpp.cpp:4:0:
/usr/local/include/asteriskcpp/manager/ManagerConnection.h:49:14: error:   initializing argument 1 of ‘void asteriskcpp::ManagerConnection::addEventCallback(asteriskcpp::onManagerEventCallback_t)’ [-fpermissive]

I tried to compile also the example located in the asterisk-cpp folder and I get error when liniking with the generated library:

root@debian:~/asterisk-cpp-master/asterisk-cpp/examples# ./makeTest.sh
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::UserEventAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::HangupAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::QueueStatusAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::QueueResetAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::PlayDtmfAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::SkypeBuddiesAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::SkypeRemoveBuddyAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::MeetMeUnmuteAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::RedirectAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `asteriskcpp::GetConfigResponse::GetConfigResponse(std::string const&)'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::DbDelAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::SkypeLicenseListAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::StopMonitorAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `asteriskcpp::ModuleCheckResponse::ModuleCheckResponse(std::string const&)'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::IaxPeerListAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `asteriskcpp::SkypeBuddyResponse::SkypeBuddyResponse(std::string const&)'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::UnpauseMonitorAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::ZapRestartAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::ParkedCallsAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::ConfbridgeUnmuteAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::ExtensionStateAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::ModuleLoadAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::SkypeLicenseStatusAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::QueueLogAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::ShowDialplanAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::ConfbridgeMuteAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::GetVarAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::ConfbridgeLockAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `asteriskcpp::PingResponse::PingResponse(std::string const&)'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::ZapShowChannelsAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::MailboxCountAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `asteriskcpp::GetVarResponse::GetVarResponse(std::string const&)'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::SendTextAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::ZapDialOffhookAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::SipShowRegistryAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `asteriskcpp::MailboxCountResponse::MailboxCountResponse(std::string const&)'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::QueueSummaryAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::CoreStatusAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::ModuleCheckAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::ParkAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::VoicemailUsersListAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::SetCdrUserFieldAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::ConfbridgeListAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::ZapTransferAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::LocalOptimizeAwayAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::QueuePauseAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::JabberSendAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `asteriskcpp::ExtensionStateResponse::ExtensionStateResponse(std::string const&)'
/usr/local/lib//libasteriskcpp.so: undefined reference to `asteriskcpp::SkypeLicenseStatusResponse::SkypeLicenseStatusResponse(std::string const&)'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::ConfbridgeSetSingleVideoSrcAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::SkypeChatSendAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::MixMonitorMuteAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::CoreShowChannelsAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::SipPeersAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `asteriskcpp::MailboxStatusResponse::MailboxStatusResponse(std::string const&)'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::MailboxStatusAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::MonitorAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::PauseMonitorAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::ConfbridgeUnlockAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::SetVarAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `asteriskcpp::CoreSettingsResponse::CoreSettingsResponse(std::string const&)'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::DahdiShowChannelsAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::DbPutAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `asteriskcpp::CoreStatusResponse::CoreStatusResponse(std::string const&)'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::ZapDndOnAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::ZapDndOffAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::ConfbridgeStartRecordAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::QueueAddAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::SkypeBuddyAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::SipShowPeerAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::ZapHangupAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::CoreSettingsAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::MeetMeMuteAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::BridgeAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::ConfbridgeStopRecordAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::SkypeAddBuddyAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::QueuePenaltyAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::PingAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::ChangeMonitorAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::DbDelTreeAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::PauseMixMonitorAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::ConfbridgeKickAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::DbGetAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::QueueRemoveAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::GetConfigAction'
/usr/local/lib//libasteriskcpp.so: undefined reference to `vtable for asteriskcpp::StatusAction'
collect2: error: ld returned 1 exit status

Can you help me to fix this error?

Thanks in advance

**Comment by omid1981** [comment]
The same problem here with some differences:

user@linux:/home/ast> g++ a.cpp -lasteriskcpp -lboost_system
/usr/local/lib/libasteriskcpp.so: undefined reference to `asteriskcpp::GetConfigResponse::GetConfigResponse(std::string const&)'
/usr/local/lib/libasteriskcpp.so: undefined reference to `asteriskcpp::ModuleCheckResponse::ModuleCheckResponse(std::string const&)'
/usr/local/lib/libasteriskcpp.so: undefined reference to `asteriskcpp::SkypeBuddyResponse::SkypeBuddyResponse(std::string const&)'
/usr/local/lib/libasteriskcpp.so: undefined reference to `asteriskcpp::PingResponse::PingResponse(std::string const&)'
/usr/local/lib/libasteriskcpp.so: undefined reference to `asteriskcpp::GetVarResponse::GetVarResponse(std::string const&)'
/usr/local/lib/libasteriskcpp.so: undefined reference to `asteriskcpp::MailboxCountResponse::MailboxCountResponse(std::string const&)'
/usr/local/lib/libasteriskcpp.so: undefined reference to `asteriskcpp::ExtensionStateResponse::ExtensionStateResponse(std::string const&)'
/usr/local/lib/libasteriskcpp.so: undefined reference to `asteriskcpp::SkypeLicenseStatusResponse::SkypeLicenseStatusResponse(std::string const&)'
/usr/local/lib/libasteriskcpp.so: undefined reference to `asteriskcpp::MailboxStatusResponse::MailboxStatusResponse(std::string const&)'
/usr/local/lib/libasteriskcpp.so: undefined reference to `asteriskcpp::CoreSettingsResponse::CoreSettingsResponse(std::string const&)'
/usr/local/lib/libasteriskcpp.so: undefined reference to `asteriskcpp::CoreStatusResponse::CoreStatusResponse(std::string const&)'
collect2: error: ld returned 1 exit status
